In [1]:
import numpy as np
from keras.datasets import mnist
import keras
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
training_set, test_set = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [3]:
X_train, y_train = training_set
X_test, y_test = test_set

In [4]:
print(X_train.shape)

(60000, 28, 28)


In [5]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

In [6]:
print(X_train.shape)

(60000, 28, 28, 1)


In [7]:
X_train = X_train.astype(np.float) / 255.0  
X_test = X_test.astype(np.float) / 255.0

<ipython-input-7-4677e48edfd8>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_train = X_train.astype(np.float) / 255.0
<ipython-input-7-4677e48edfd8>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_test = X_test.astype(np.float) / 255.0


In [8]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

In [9]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [12]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 3s 5ms/step - loss: 0.7515 - accuracy: 0.8150 - val_loss: 0.4074 - val_accuracy: 0.8986
Epoch 2/30
375/375 [==============================] - 1s 3ms/step - loss: 0.3899 - accuracy: 0.8964 - val_loss: 0.3353 - val_accuracy: 0.9087
Epoch 3/30
375/375 [==============================] - 1s 3ms/step - loss: 0.3386 - accuracy: 0.9071 - val_loss: 0.3068 - val_accuracy: 0.9166
Epoch 4/30
375/375 [==============================] - 1s 3ms/step - loss: 0.3146 - accuracy: 0.9137 - val_loss: 0.2927 - val_accuracy: 0.9189
Epoch 5/30
375/375 [==============================] - 1s 3ms/step - loss: 0.3004 - accuracy: 0.9168 - val_loss: 0.2835 - val_accuracy: 0.9217
Epoch 6/30
375/375 [==============================] - 1s 3ms/step - loss: 0.2907 - accuracy: 0.9192 - val_loss: 0.2788 - val_accuracy: 0.9216
Epoch 7/30
375/375 [==============================] - 1s 3ms/step - loss: 0.2837 - accuracy: 0.9206 - val_loss: 0.2745 - val_accuracy: 0.9254
Epoch 

In [13]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 1s 3ms/step
              precision    recall  f1-score   support

           0       0.95      0.98      0.96       980
           1       0.97      0.98      0.97      1135
           2       0.93      0.89      0.91      1032
           3       0.89      0.92      0.90      1010
           4       0.94      0.94      0.94       982
           5       0.91      0.86      0.89       892
           6       0.95      0.94      0.95       958
           7       0.93      0.93      0.93      1028
           8       0.87      0.90      0.88       974
           9       0.91      0.91      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 965    0    1    2    0    5    4    2    1    0]
 [   0 1112    3    3    0    1    3    2   11    0]
 [   7   10  917   20    8    3   12   10   42    3]
 [   3    0   15  925    0 

In [14]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_1 (Dense)             (None, 64)                50240     
                                                                 
 dense_2 (Dense)             (None, 128)               8320      
                                                                 
 dense_3 (Dense)             (None, 10)                1290      
                                                                 
Total params: 59,850
Trainable params: 59,850
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [17]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 3s 7ms/step - loss: 0.4124 - accuracy: 0.8849 - val_loss: 0.2235 - val_accuracy: 0.9351
Epoch 2/30
375/375 [==============================] - 2s 5ms/step - loss: 0.1975 - accuracy: 0.9420 - val_loss: 0.1678 - val_accuracy: 0.9536
Epoch 3/30
375/375 [==============================] - 2s 5ms/step - loss: 0.1435 - accuracy: 0.9570 - val_loss: 0.1397 - val_accuracy: 0.9576
Epoch 4/30
375/375 [==============================] - 2s 4ms/step - loss: 0.1115 - accuracy: 0.9670 - val_loss: 0.1243 - val_accuracy: 0.9637
Epoch 5/30
375/375 [==============================] - 2s 4ms/step - loss: 0.0898 - accuracy: 0.9740 - val_loss: 0.1195 - val_accuracy: 0.9647
Epoch 6/30
375/375 [==============================] - 2s 6ms/step - loss: 0.0740 - accuracy: 0.9781 - val_loss: 0.1086 - val_accuracy: 0.9669
Epoch 7/30
375/375 [==============================] - 3s 8ms/step - loss: 0.0621 - accuracy: 0.9817 - val_loss: 0.1096 - val_accuracy: 0.9682
Epoch 

In [18]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 1s 2ms/step
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.96      0.97      0.97      1032
           3       0.96      0.97      0.97      1010
           4       0.98      0.97      0.98       982
           5       0.97      0.96      0.97       892
           6       0.98      0.97      0.98       958
           7       0.97      0.97      0.97      1028
           8       0.97      0.97      0.97       974
           9       0.98      0.97      0.97      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

[[ 969    0    2    1    0    2    3    2    1    0]
 [   0 1123    4    2    0    1    1    2    2    0]
 [   6    1 1000    3    1    2    3    7    9    0]
 [   1    0    8  983    0 

In [19]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )

In [20]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten_2 (Flatten)         (None, 1600)              0         
                                                                 
 dropout (Dropout)           (None, 1600)             

In [21]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [22]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 44s 115ms/step - loss: 0.3880 - accuracy: 0.8864 - val_loss: 0.1034 - val_accuracy: 0.9721
Epoch 2/30
375/375 [==============================] - 45s 121ms/step - loss: 0.1205 - accuracy: 0.9626 - val_loss: 0.0709 - val_accuracy: 0.9793
Epoch 3/30
375/375 [==============================] - 44s 116ms/step - loss: 0.0922 - accuracy: 0.9711 - val_loss: 0.0596 - val_accuracy: 0.9822
Epoch 4/30
375/375 [==============================] - 45s 119ms/step - loss: 0.0737 - accuracy: 0.9766 - val_loss: 0.0505 - val_accuracy: 0.9853
Epoch 5/30
375/375 [==============================] - 44s 118ms/step - loss: 0.0658 - accuracy: 0.9792 - val_loss: 0.0464 - val_accuracy: 0.9867
Epoch 6/30
375/375 [==============================] - 43s 114ms/step - loss: 0.0588 - accuracy: 0.9815 - val_loss: 0.0421 - val_accuracy: 0.9876
Epoch 7/30
375/375 [==============================] - 43s 115ms/step - loss: 0.0527 - accuracy: 0.9836 - val_loss: 0.0404 - val_ac

In [23]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 3s 9ms/step
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       1.00      1.00      1.00      1135
           2       0.99      0.99      0.99      1032
           3       0.99      1.00      0.99      1010
           4       0.99      0.99      0.99       982
           5       0.99      0.99      0.99       892
           6       1.00      0.99      0.99       958
           7       0.99      0.99      0.99      1028
           8       0.99      0.99      0.99       974
           9       0.99      0.99      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

[[ 977    1    0    0    0    0    0    1    1    0]
 [   0 1132    3    0    0    0    0    0    0    0]
 [   1    0 1023    0    1    0    0    6    1    0]
 [   0    0    2 1005    0 